#!/bin/bash

echo "================================================"
echo "🔧 BREVO API KEY SETUP INSTRUCTIONS"
echo "================================================"
echo ""
echo "To fix the email issue, follow these steps:"
echo ""
echo "1. Open your browser and go to:"
echo "   👉 https://app.brevo.com/"
echo ""
echo "2. Login to your Brevo account"
echo ""
echo "3. Navigate to: SMTP & API → API Keys"
echo "   (Click your profile icon → SMTP & API → API Keys tab)"
echo ""
echo "4. Click 'Generate a new API key' or copy existing one"
echo ""
echo "5. Copy the API key"
echo ""
echo "6. Open the file: backend/.env"
echo ""
echo "7. Find this line:"
echo "   # BREVO_API_KEY=your_brevo_api_key_here"
echo ""
echo "8. Uncomment it and replace with your actual key:"
echo "   BREVO_API_KEY=xkeysib-your-actual-key-here"
echo ""
echo "9. Save the file"
echo ""
echo "10. Restart the backend server:"
echo "    - Stop the current server (Ctrl+C in the terminal)"
echo "    - Run: cd backend && node server.js"
echo ""
echo "11. Test the contact form again!"
echo ""
echo "================================================"
echo "✅ This will fix the 'Unauthorized IP' error!"
echo "================================================"
